version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      bash -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...';
          sleep 1;
        done;
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails s -b 0.0.0.0 -p 3000
      "
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

volumes:
  data:

networks:
  default:
    driver: bridge
