version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
volumes:
  data:
