version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"

    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/bd_production"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

volumes:
  data:
